# hydra_configs/configs.yaml

defaults:
  - experiment: live_zmq
  - _self_

eval: false

hydra:
  job:
    chdir: false
  run:
    # 실행 시 생성되는 로그와 출력물의 저장 경로 (실행 시간별로 폴더 생성)
    dir: ../gsSLAM-outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null